export const REG_TOTAL_CARS = "totalCars";
export const REG_HUMAN_CARS = "humanCars";
export const REG_BOT_CARS = "botCars";
export const REG_RACE_LAPS = "raceLaps";
export const PIT_LANE = 0;
export const MAIN_LANES = [1, 2, 3] as const;
export const INNER_MAIN_LANE = MAIN_LANES[0];
export const MIDDLE_MAIN_LANE = MAIN_LANES[1];
export const OUTER_MAIN_LANE = MAIN_LANES[2];
